name: RUN_SCRIPT

on:
  # ==== Dispatch Manual ==== #
  workflow_dispatch:
  # ==== Dispatch Automatic ==== #
  schedule:
    - cron: '0 0 * * 1-5'


jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      # ================================== #
      # ======== 1. DOWNLOAD REPO ======== #
      # ================================== #
      - name: DOWNLOAD REPO
        uses: actions/checkout@v3
      
        
      # ================================= #
      # ======== 2. SETUP PYTHON ======== #
      # ================================= #
      - name: SETUP PYTHON
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'


      # =============================== #
      # ======== 3. CACHE LIBS ======== #
      # =============================== #
      - name: CACHE LIBS
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      # ================================= #
      # ======== 4. INSTALL LIBS ======== #
      # ================================= #
      - name: INSTALL LIBS
        run: |
          pip install -r requirements.txt


      # ================================ #
      # ======== 5. EXEC SCRIPT ======== #
      # ================================ #
      - name: EXEC SCRIPT
        run: |
          python -c "print('EXEC SCRIPT')"
          jupyter nbconvert --execute --inplace Script.ipynb
        # python Script.py


      # ================================ #
      # ======== 6. COMMIT PUSH ======== #
      # ================================ #
      - name: COMMIT PUSH
        run: |
          git config --local user.name  "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add *
          git commit -m "."
          git push
